### ISSUE TITLE
JavaScriptOFF端末向けの配慮

### ISSUE THREAD

**Issue by tatesuke** [tatesuke/KanTanMarkdown#109]
現状、JavascriptがOFFの端末では内容が一切閲覧できない。せめてMarkdownのテキストエリアぐらい表示してもいいんじゃないか

**Comment by nacika-ins** [comment]
Mac で スペースを押したときのプレビューや、スマホのSlackアプリで見た場合などに、困ることが多いですね。

**Comment by tatesuke** [comment]
ちょっと気になりますね。少し詳しく教えていただけますか？？
