### ISSUE TITLE
[License]このKanTanMarkdownのライセンスはなんですか？

### ISSUE THREAD

**Issue by fu7mu4** [tatesuke/KanTanMarkdown#11]
このKanTanMarkdownのライセンスはなんですか？
ktm.html中に記載していただけないでしょうか？

**Comment by tatesuke** [comment]
MITライセンスにしようと思います。
今日の夕方ごろにプッシュします。

まともにgitやgithubで運用するのが初めてなのでお作法がわからないところがあり、
使い方におかしな点があればご指摘いただけると幸いです。
