### ISSUE TITLE
[License] jqueryのライセンス

### ISSUE THREAD

**Issue by fu7mu4** [tatesuke/KanTanMarkdown#12]
ktm.htmlにjqueryのライセンスが記載されていないように見えます。
330行目あたりの
/_! jQuery v1.12.0 | (c) jQuery Foundation | jquery.org/license */
を
/_! jQuery v1.12.0 | (c) jQuery Foundation | jquery.org/ MIT license */
に変更してはいかがでしょうか？

**Comment by tatesuke** [comment]
jquery.min.jsをそのまま持ってきたらこうなってしまいました。
非圧縮版のヘッダを貼り付けようと思います。

```
/*!
 * jQuery JavaScript Library v1.12.0
 * http://jquery.com/
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: 2016-01-08T19:56Z
 */
```
