### ISSUE TITLE
既存のファイルに[新規]というボタンがほしいです。

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#68]
空のファイルを編集するのではなく、新規ボタンがあると便利だと思いました。

**Comment by nacika-ins** [comment]
追記です。

新規ボタンを押したことによって、データが消えたり、古いバージョンを使い続けることになると思うので、window.open によって新しいタブで「 http://tatesuke.github.io/KanTanMarkdown/ktm.html 」 を開くような仕組みがベストだと思いました。

**Comment by tatesuke** [comment]
【メモ】
画面左上に「メニュー」というようなボタンを設けて、それを押すと
- KantanMakrdownという名称とバージョン
  - いままではソースを見ないとKantanMarkdownという名称であることすらわからなかった。
  - 同じく、使っているバージョンがわからない（あまり気にすることはないかもしれないけど）
- 新規作成リンク
  - （http://tatesuke.github.io/KanTanMarkdown/ktm.html への単なるリンク）
- 記法リンク
  - (http://tatesuke.github.io/KanTanMarkdown/syntax.html への単なるリンク)

を表示するイメージ。ポップアップを実装するのは、面倒なのでモーダルウィンドウかなぁ・・・

**Comment by tatesuke** [comment]
v1.20160216.01にて対応しました

**Comment by nacika-ins** [comment]
ありがとうございます！
