### ISSUE TITLE
Ctrl+矢印(Cmd+矢印) は 文字列の選択のショートカットとバッティングしています

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#69]
Altキーにするや、Altキーに組み合わせるなどはできないでしょうか？

Ctrl+Shiftもバッティングします。

**Comment by nacika-ins** [comment]
おお！さっそくの対応ありがとうございました。

**Comment by nacika-ins** [comment]
関係ないですが、 Ironというブラウザを使うと、 AtomやKobitoを使うよりもCPU使用率がとても少なく、バッテリーを長持ちさせることが出来ます。とても便利です。ありがとうございます。

**Comment by tatesuke** [comment]
よく使うショートカットキーは使い勝手に直結するので今回のバッティングは致命的でした・・・
気づいてもらえてスルーせずに報告してもらえて助かりましたm_ _m

バッテリー消費量のことなんて考えたこともありませんでした(・o・)
意外な利点ですｗ
