### ISSUE TITLE
Ctrl+vを離さずに押しっぱなしにして連続ペーストすると元に戻るが効かないことがある

### ISSUE THREAD

**Issue by tatesuke** [tatesuke/KanTanMarkdown#73]
![test](https://cloud.githubusercontent.com/assets/1269617/12887059/2ee1223a-ceb5-11e5-9e88-d63587d080b1.gif)

**Comment by tatesuke** [comment]
v1.20160208.01にて対応しました。

**Comment by nacika-ins** [comment]
:+1:
