### ISSUE TITLE
デフォルトで「添付ファイルを表示」を非表示にしてほしい

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#74]
小さな画面のPCで入力しているのでデフォルトで閉じられていたほうが大変使い勝手が良いと思いました。

**Comment by tatesuke** [comment]
ありがとうございます。私もうすうす感じておりました…（笑）

瞬殺なので今日中に直しておきます。

**Comment by nacika-ins** [comment]
ありがとうございます！

**Comment by tatesuke** [comment]
v1.20160208.01にて対応しました。

ついでにファイルをドロップしたら添付ファイル領域を開くようにしました。

**Comment by nacika-ins** [comment]
ありがとうございます！:+1:
