### ISSUE TITLE
画像の埋め込み型よくわからなかったです。

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#76]
当方Mac+Chromeですがうまく埋め込むことができませんでした。

![image](https://cloud.githubusercontent.com/assets/1073376/12917949/b13e63b2-cf7f-11e5-9f3e-e554b21c805c.png)

![image](https://cloud.githubusercontent.com/assets/1073376/12917957/b96475cc-cf7f-11e5-8e41-0a2a87eb5cdc.png)

**Comment by tatesuke** [comment]
imgタグを使ってみてください。

```
<img name="画像名">
```

**src属性ではなくname属性**

というようにしてみください

**Comment by tatesuke** [comment]
あまり重い画像を入れると急激に重くなるので注意です

**Comment by nacika-ins** [comment]
なるほど！ ありがとうございます！
HTMLも使えたのですね。
