### ISSUE TITLE
ctrl+s(cmd+s)で保存したときに、保存されていないことになり確認画面がでてウィンドウが閉じれない

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#83]
ctrl+s(cmd+s)を押してすぐに閉じようとすると

```
ドキュメントが保存されていません。
このページから移動してもよろしいですか？
```

が出ます。

**Comment by tatesuke** [comment]
これは大至急調査します

**Comment by nacika-ins** [comment]
そこまで困っているわけではないので大丈夫です！

**Comment by tatesuke** [comment]
あれ、もしかしてこれって昔からでした・・・・！？

**Comment by nacika-ins** [comment]
はい！

**Comment by tatesuke** [comment]
コードを見たらデグレではなさそうだったので・・・ｗ

あれ？自分でも使ってたんですけどね・・・全然気づきませんでした｡ﾟ(ﾟ^Д^)ﾟ｡
そう言われてみればやたらと警告は出た気が・・・・

明日くらいに#80と一緒に直します。

**Comment by tatesuke** [comment]
keyupイベントで一律変更と判断してしまったのが原因でした。
inputイベントで判断するように修正しました。

**Comment by nacika-ins** [comment]
:+1:
