### ISSUE TITLE
未保存のウィンドウを閉じた時にlocalStorageに現在のバッファを保持する機能

### ISSUE THREAD

**Issue by nacika-ins** [tatesuke/KanTanMarkdown#92]
未保存のウィンドウを閉じたときに、localStorageに現在のバッファを保持し、再度新規ファイルを開いたときにデフォルトで呼び出す機能が欲しいです。

**Comment by tatesuke** [comment]
なるほど、なかなか便利そうではありますがちょっと見送りたいです。
理由は主に3つあって、
- 私自身が「いったんまっさらにしよう」という意味でわざと保存しないで閉じることがある。
  - 保存して、ちょっと加筆した後やっぱり保存時まで戻したいこともある
- 文章が他人に復元されるセキュリティのリスク（同一端末で複数人触ることもありうる）
- かんたんMarkdownを複数タブ開いてて一気に閉じるときに最後のしか残らない

セキュリティに関しては「キャッシュ残ってるかもよ？」とか、「今更かよ感」とかありますが、
一応閉じる前に警告する機能はついてますし、今のままがシンプルかなと思っています。
どう思われますか？

**Comment by nacika-ins** [comment]
なるほどですねー了解です！
どうしても必要なとき改めて考えてみます！

**Comment by tatesuke** [comment]
m_ _m
