### ISSUE TITLE
IEだと編集モードに切り替えるだけで変更ありになってしまう

### ISSUE THREAD

**Issue by tatesuke** [tatesuke/KanTanMarkdown#96]

**Comment by tatesuke** [comment]
デグレ。修正済み。次のリリースで反映

#83で``saved`フラグをinputイベントでfalseにするように変更したのが原因。
IEではなぜかinputイベントを発生させてしまうらしい。

---

以下の方式に修正した。
1. 起動時、保存時に 内容を保存
2. nputイベント時に1の値とエディタの値を比較
   1. 変更がなければ``saved`フラグを`false`にする
   2. 変更があれば``saved`フラグを`true`にする

この変更によって、このバグと、他に変更マークの挙動が改善する。
いままでは一度変更したら保存するまで変更マークは消えなかったが、編集前の値に戻したら変更マークが消えるようになった。

**Comment by nacika-ins** [comment]
:+1:
